spring:
  application:
    name: order-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/order_service?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Nhey1123@

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      inventory-service: # CircuitBreaker name not a property
        register-health-indicator: true
        sliding-window-size: 5
        sliding-window-type: COUNT_BASED
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      inventory-service: # CircuitBreaker name not a property
        timeout-duration: 3s
  retry:
    instances:
      inventory-service: # CircuitBreaker name not a property
        max-attempts: 3
        wait-duration: 5s
