spring:
  application:
    name: inventory-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Nhey1123@
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
